---
services:
  traefik:
    networks:
      ocis-net:
        aliases:
          - ${COMPANION_DOMAIN:-companion.owncloud.test}

  companion:
    # companion could be updated to: 4.14.0 <-- needs checking 
    image: ${COMPANION_IMAGE:-transloadit/companion:4.5.1}
    networks:
      - ocis-net
    environment:
      NODE_ENV: production
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      COMPANION_DATADIR: /tmp/companion/
      COMPANION_DOMAIN: ${COMPANION_DOMAIN:-companion.owncloud.test}
      COMPANION_PROTOCOL: https
      COMPANION_UPLOAD_URLS: "^https://${OCIS_DOMAIN:-ocis.owncloud.test}/"
      COMPANION_ONEDRIVE_KEY: "${COMPANION_ONEDRIVE_KEY}"
      COMPANION_ONEDRIVE_SECRET: "${COMPANION_ONEDRIVE_SECRET}"
    volumes:
      - companion-data:/tmp/companion/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.companion.entrypoints=https"
      - "traefik.http.routers.companion.rule=Host(`${COMPANION_DOMAIN:-companion.owncloud.test}`)"
      - "traefik.http.routers.companion.tls.certresolver=http"
      - "traefik.http.routers.companion.service=companion"
      - "traefik.http.services.companion.loadbalancer.server.port=3020"
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always

volumes:
  companion-data:

