---
exclude_paths:
  - 'CHANGELOG.md'
  - '**/CHANGELOG.md'
  - 'changelog/**'
  - '**/changelog/**'
  - 'docs/**'
  - '**/docs/**'
  - '**/pkg/proto/**'
  - 'konnectd/assets/identifier/**'
  - 'settings/rollup.config.js'
  - 'accounts/rollup.config.js'

...