---
debug:
  addr: 0.0.0.0:8090
  token:
  pprof: false

http:
  addr: 0.0.0.0:8080
  root: /

asset:
  path:

config:
  custom:
  server:
  theme: owncloud
  version: 0.1.0
  client:
  apps:
    - files

...
