baseURL = "https://owncloud.github.io/ocis/"
languageCode = "en-us"
title = "ownCloud Infinite Scale Stack"
pygmentsUseClasses = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "ownCloud GmbH"
  description = "Launch all oCIS services"
  keywords = "reva, ocis"
